spring:
  application:
    name: review-service

server:
  port: 19097

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/
