spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${REVIEW_PROD_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REVIEW_REDIS_HOST}
      port: ${REVIEW_REDIS_PORT}
      username: ${REVIEW_REDIS_USERNAME}
      password: ${REVIEW_REDIS_PASSWORD}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:19090/eureka/