spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${USER_PROD_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:19090/eureka/

service:
  jwt:
    access-expiration: 3600000  # 1시간
    secret-key: ${JWT_SECRET_KEY}


management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: "/api/v1/users/actuator"
  endpoint:
    health:
      show-details: always

    prometheus:
      enabled: true