spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${USER_PROD_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
