services:
  eureka:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./eureka
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/eureka

  gateway:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./gateway
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/gateway
    ports:
      - "8080:8080"

  user:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./user
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/user

  review:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./review
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/review

  review-redis:
    image: "redis/redis-stack"
    container_name: review-redis-prod
    restart: always
    ports:
      - "${REVIEW_REDIS_PORT}:6379"
    environment:
      - REDIS_ARGS=--requirepass ${REVIEW_REDIS_PASSWORD}
    volumes:
      - review-redis-prod-data:/data
      - review-redis-config-file:/usr/local/etc/redis/redis.conf

volumes:
  review-redis-prod-data:
  review-redis-config-file: