services:
  eureka:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./eureka
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/eureka

  gateway:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./gateway
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/gateway
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

    ports:
      - "8080:8080"

  user:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./user
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/user
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - USER_PROD_DB_NAME=${USER_PROD_DB_NAME}

  review:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./review
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/review
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REVIEW_PROD_DB_NAME=${REVIEW_PROD_DB_NAME}
      - REVIEW_REDIS_HOST=${REVIEW_REDIS_HOST}
      - REVIEW_REDIS_PORT=${REVIEW_REDIS_PORT}
      - REVIEW_REDIS_USERNAME=${REVIEW_REDIS_USERNAME}
      - REVIEW_REDIS_PASSWORD=${REVIEW_REDIS_PASSWORD}

  review-redis:
    image: "redis/redis-stack"
    container_name: review-redis-prod
    restart: always
    ports:
      - "${REVIEW_REDIS_PORT}:6379"
    environment:
      - REDIS_ARGS=--requirepass ${REVIEW_REDIS_PASSWORD}
    volumes:
      - review-redis-prod-data:/data
      - review-redis-config-file:/usr/local/etc/redis/redis.conf

  performance:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./performance
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/performance
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PERFORMANCE_PROD_DB_NAME=${PERFORMANCE_PROD_DB_NAME}
      - PERFORMANCE_REDIS_HOST=${PERFORMANCE_REDIS_HOST}
      - PERFORMANCE_REDIS_PORT=${PERFORMANCE_REDIS_PORT}
      - PERFORMANCE_REDIS_USERNAME=${PERFORMANCE_REDIS_USERNAME}
      - PERFORMANCE_REDIS_PASSWORD=${PERFORMANCE_REDIS_PASSWORD}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}

  performance-redis:
    image: "redis/redis-stack"
    container_name: performance-redis-prod
    restart: always
    ports:
      - "${PERFORMANCE_REDIS_PORT}:6379"
    environment:
      - REDIS_ARGS=--requirepass ${PERFORMANCE_REDIS_PASSWORD}
    volumes:
      - performance-redis-prod-data:/data
      - performance-redis-config-file:/usr/local/etc/redis/redis.conf

  order:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./order
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/order
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ORDER_PROD_DB_NAME=${ORDER_PROD_DB_NAME}
      - ORDER_REDIS_HOST=${ORDER_REDIS_HOST}
      - ORDER_REDIS_PORT=${ORDER_REDIS_PORT}
      - ORDER_REDIS_USERNAME=${ORDER_REDIS_USERNAME}
      - ORDER_REDIS_PASSWORD=${ORDER_REDIS_PASSWORD}

  order-redis:
    image: "redis/redis-stack"
    container_name: order-redis-prod
    restart: always
    ports:
      - "${ORDER_REDIS_PORT}:6379"
    environment:
      - REDIS_ARGS=--requirepass ${ORDER_REDIS_PASSWORD}
    volumes:
      - order-redis-prod-data:/data
      - order-redis-config-file:/usr/local/etc/redis/redis.conf

  payment:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./payment
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/payment
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PAYMENT_PROD_DB_NAME=${PAYMENT_PROD_DB_NAME}

volumes:
  review-redis-prod-data:
  review-redis-config-file:
  performance-redis-prod-data:
  performance-redis-config-file:
  order-redis-prod-data:
  order-redis-config-file:
