global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'performance-service'
    metrics_path: '/api/v1/performances/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:19094']

  - job_name: 'user-service'
    metrics_path: '/api/v1/users/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19093' ]

  - job_name: 'review-service'
    metrics_path: '/api/v1/reviews/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19097' ]

  - job_name: 'order-service'
    metrics_path: '/api/v1/orders/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19095' ]

  - job_name: 'payment-service'
    metrics_path: '/api/v1/payments/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19096' ]



