server:
  port: 8080

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:19090/eureka/
