version: "3"
services:
  review-db:
    image: "postgres"
    container_name: review-db-local-1
    restart: always
    ports:
      - "${REVIEW_DB_PORT}:5432"
    volumes:
      - review-postgres-local-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${REVIEW_POSTGRES_USER}
      - POSTGRES_PASSWORD=${REVIEW_POSTGRES_PASSWORD}
    env_file:
      - .env

volumes:
  review-postgres-local-data: