eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:19090/eureka/
