eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/
spring:
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: jdbc:postgresql://${url}/payment
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


rest:
  api:
    key: ${portone-rest-api-key}
    secret: ${portone-rest-api-secret}
