spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${PERFORMANCE_PROD_DB_NAME}?rewriteBatchedInserts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
    generate-ddl: true
    database: postgresql

  data:
    redis:
      host: ${PERFORMANCE_REDIS_HOST}
      port: ${PERFORMANCE_REDIS_PORT}
      username: ${PERFORMANCE_REDIS_USERNAME}
      password: ${PERFORMANCE_REDIS_PASSWORD}

s3:
  credentials:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ap-northeast-2
  bucket: ${S3_BUCKET_NAME}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server:19090/eureka/