spring:
  application:
    name: performance-service

server:
  port: 19094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/
