spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: performance-service
  datasource:
    url: jdbc:postgresql://${url}/performance
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: ${redis-url}
      port: ${redis-port}
      username: ${redis-username}
      password: ${redis-password}


server:
  port: 19094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/
